namespace NetRatel.Mcp.Core;

/// <summary>Instructions for the canonical V2 surface, shared by tool and resource discovery.</summary>
internal static class NetRatelMcpOperatorInstructions
{
    public static string Describe(NetRatelMcpToolDescriptor tool)
    {
        var instructions = tool.Name switch
        {
            "netratel_clients" => "Inspect or administer one persisted V2 client using tenantId and agentId from search. get returns durable metadata; presence/capabilities report current gateway state; telemetry returns a snapshot. binding is optional provenance: hasBinding=false is normal for native V2 clients. update_metadata and update_attempts expose update policy and history. Ping, software_update, disable, enable and delete each require their matching preview_* credentials followed by confirm:true. Ping needs an online client. software_update only resumes suspended automatic-update eligibility; it does not select or upload a package. Disabled clients remain administratively readable and can be enabled or deleted. Delete revokes credentials and retains a historical tombstone. Confirm installed version and gateway presence before declaring an update successful.",
            "netratel_files" => "Use browse/stat/read for an exact tenantId, agentId and canonical path. Browse supports bounded pageSize; read is byte-bounded. Inspect capabilities for the file gateway and allowed roots. Mutations use matching preview_* then confirm_* operations with unchanged inputs, planToken, idempotencyKey and confirm:true. write_text preserves supplied whitespace and newlines; upload/download use base64 bytes and transfer metadata. Verify actual content or hash after a write. Copy, move and delete operate only on the admitted paths. Download artifacts use the returned artifact identifier. Never infer success from a preview or expose opaque credentials.",
            "netratel_client_logs" => "Discover sources first for one tenantId and agentId. Choose an available sourceId, then use bounded history/search or tail windows. Follow returned cursors and resync guidance. preview_resync binds the source; confirm_resync requires unchanged credentials and confirm:true. Check resyncCompleted before opening a new tail. Source availability depends on the client platform and installed logging providers.",
            "netratel_client_telemetry" => "Read one client's current V2 gateway telemetry with exact tenantId and agentId. snapshot and bounded stream return observed data and timestamps; inspect freshness and availability before drawing conclusions. These calls do not collect arbitrary endpoint commands.",
            "netratel_jobs" => "Manage caller-owned job definitions for one tenantId and agentId. Create a reviewed library script first; add steps with its current scriptId, version and contentHash. Preserve decimal-string job and item IDs exactly. Reads include list/get/details/params/steps; validate checks a draft. Mutations return a preview: repeat unchanged inputs with confirm:true and its planToken/idempotencyKey. Use the returned version as expectedVersion for the next definition mutation. Execute with netratel_job_runs/start. Deleting a definition prevents new execution and retains historical runs.",
            "netratel_job_runs" => "Start, inspect, cancel or delete caller-owned job runs for one tenantId and agentId. IDs are exact decimal strings. Mutations require preview credentials and confirm:true. Poll get until Succeeded, Failed, Cancelled or TimedOut; acceptance alone is not completion. Read steps and bounded redacted logs to verify stdout/stderr. Logs use streamed rows or the persisted gateway result. Cancel active runs; delete terminal retained runs. Historical runs remain owned and readable after definition deletion.",
            "netratel_tenants" => "Discover tenants with list/get, or netratel_search/tenants for read-scoped lookup. Tenant administration is a control-plane operation with no agent target. Create/update/delete require admin scope and an applicable policy. Mutations return a preview; repeat unchanged inputs with confirm:true and its credentials. Updates/deletes require current expectedVersion. Deletion reports dependent counts and supports only cascade:false with no remaining dependencies.",
            "netratel_scripts" => "Use exact tenantId and agentId. Full-Dev admission lists the canonical shared library, including UI and other-operator sources: list accepts afterId/limit (continue from the last scriptId) and get exposes definitionScope, sourceRevision and executionEligible. Canonical CRUD uses source:{name,content,scriptType,folderPath?,description?,manifestJson?}; update/parse_manifest/delete require the observed expectedSourceRevision and expectedContentHash. Preview and confirm bind that revision/hash; reload and preview again after a conflict. Canonical source edits create no execution review. Global source execution is not available through this slice; run requires executionEligible plus reviewedVersion as version and the current contentHash, and remains subject to execution admission. Narrower Dev and Production retain caller-owned scripts. The existing reviewed script workflow uses validate before create to check content, shell, parameters, side effects and SHA-256 contentHash. Mutation previews return planToken/idempotencyKey; repeat unchanged inputs with confirm:true. Reviewed-script update/parse_manifest/delete use expectedVersion. Run requires the current version/hash and returns taskId plus requestId. Poll netratel_tasks/get until Completed, Failed or Cancelled; inspect resultSummary and logs/logs_by_request. Cancel a running script through netratel_tasks/cancel. Keep content and credentials out of audit descriptions.",
            "netratel_terminal" => "Check availability, then preview_open and confirmed open for one tenantId/agentId. Poll get until opened before send_input. Send commands with the required newline. stream_window is a replayable bounded output window: pass returned decimal-string nextSequence as afterSequence on the next poll. An initial page may contain only a prompt. Follow hasMore; gap means output was lost. History is limited to 64 frames / 1 MiB and is lost on API restart. resize and close require confirmation; always close the session after use. Use diagnostics for session state.",
            "netratel_commands" => "Check availability, obtain preview_execute credentials, then execute with unchanged inputs and confirm:true for one tenantId/agentId. Shell commands require the applicable execution policy and destructive confirmation. Poll get until terminal state and inspect output.exitCode, stdout, stderr, outputTruncated and unavailableReason. cancel requests cancellation; verify the resulting terminal state. environmentReferences are names of client-local values, never secret values. Command output is bounded and redacted.",
            "netratel_onboarding" => "Inspect collateral and create an enrollment for a tenant before installing a new client. Create/revoke use preview credentials and confirm:true. The raw enrollment code appears only in the first confirmed creation response; never log it. collateral_download returns inline contentBase64 for small files or enrollment_download with a version-pinned path and header names. GET that path on the same API origin, supply credentials only in the specified headers, and verify size/SHA-256. Download does not consume an enrollment use. Inspect enrollment usage after client admission and revoke disposable codes.",
            "netratel_tasks" => "Inspect caller-owned tasks using exact tenantId/agentId and decimal-string taskId. create_command and run_library_script return previews; repeat unchanged inputs with confirm:true and their credentials. Poll get: state is inside data.task; terminal states include Completed, Failed and Cancelled. Inspect resultSummary and logs; logs_by_request resolves the returned requestId. cancel uses its own preview/confirmation and must be followed by a terminal-state check. list/recent are bounded discovery reads.",
            "netratel_requests" => "Manage requests linked to one owned job and exact tenantId/agentId. Create, update, claim, complete, fail and cancel require a preview and confirmed unchanged request. Read get after mutations to obtain data.request.version for the next expectedVersion. Completed, Failed and Cancelled are terminal states. Request lifecycle changes do not themselves prove job execution; inspect the linked job run separately.",
            "netratel_notifications" => "Read notifications belonging to the signed-in operator with list/get/summary/unread_errors. mark_read first returns a preview; repeat the selected IDs with its credentials and confirm:true, then verify read state. List accepts one-based page and pageSize (1–100); use totalCount to continue paging. This is caller-specific control-plane data.",
            "netratel_connectivity" => "Inspect redacted server-owned configuration with settings/netratel. preview_test returns credentials for one bounded ExternalService connectivity probe; test requires confirm:true. Inspect each probe's status and HTTP status: successful tool delivery can contain a Red or Amber downstream result. No endpoint override is accepted and no credential or response body is exposed.",
            "netratel_events" => "Read bounded outbox event summaries with list/get. List accepts one-based page and pageSize (1–100); continue until a page is shorter than pageSize. For one exact eligible event, preview_retry or preview_disable returns credentials; retry/disable requires unchanged eventId, credentials and confirm:true. Inspect the resulting event state. Retry has external callback effects; payloads and callback credentials remain server-side.",
            _ => null
        };
        if (instructions is null) return tool.Description;
        var operations = tool.Operations.Where(operation => operation.IsAvailableOverHttpIn("prod")).Select(operation => operation.Name);
        return $"{instructions} Operations: {string.Join(", ", operations)}. Use the current server's environment; supply only fields in the selected operation's request schema.";
    }
}
