server {
    listen 443 ssl;
    server_name _;
    ssl_certificate /run/netratel-ingress/tls.crt;
    ssl_certificate_key /run/netratel-ingress/tls.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 1g;

    location / {
        proxy_pass http://web:9111;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
    }
}
