<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RazorLangVersion>Latest</RazorLangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Microsoft.Playwright" Version="1.62.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="../NetRatel.Web/obj/$(Configuration)/$(TargetFramework)/scopedcss/bundle/NetRatel.Web.styles.css" Link="NetRatel.Web.styles.css" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="$(NuGetPackageRoot)/mudblazor/8.13.0/staticwebassets/MudBlazor.min.css" Link="MudBlazor.min.css" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetRatel.Web\NetRatel.Web.csproj" />
  </ItemGroup>

</Project>
