using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NetRatel.Client.Data.PowerShell
{
    /// <summary>
    /// Represents the result of executing a PowerShell command.
    /// </summary>
    public class CommandResult
    {
        /// <summary>
        /// Indicates whether the command executed without terminating errors.
        /// Note: Non-terminating errors might still be present in ErrorMessages.
        /// </summary>
        public bool Success { get; internal set; } = true;

        /// <summary>
        /// List of structured output objects returned by the command.
        /// Each dictionary represents an object with its properties (keys) and values.
        /// </summary>
        public List<Dictionary<string, object?>> StructuredOutput { get; } = new List<Dictionary<string, object?>>();

        /// <summary>
        /// List of raw string outputs (e.g., from Write-Host, Write-Output of simple strings).
        /// Useful if the command doesn't produce structured objects.
        /// </summary>
        public List<string> StringOutput { get; } = new List<string>();

        /// <summary>
        /// List of error messages generated by the PowerShell command.
        /// </summary>
        public List<string> ErrorMessages { get; } = new List<string>();

        /// <summary>
        /// An exception caught during the C# execution process itself (e.g., assembly load failure),
        /// not an error from within the PowerShell script.
        /// </summary>
        public Exception? ExecutionException { get; internal set; }

        /// <summary>
        /// Indicates if any errors occurred, either terminating or non-terminating,
        /// or if a C# execution exception happened.
        /// </summary>
        public bool HasErrors => ErrorMessages.Count > 0 || ExecutionException != null || !Success;
    }
}
