namespace NetRatel.Shared.Contracts.Terminals;

public enum TerminalTransportKind
{
    Auto,
    ApiWebSocket,
    // Retained solely to deserialize historical settings and records.
    Spacetime,
    AkkaGateway
}

public sealed record OpenTerminalRequest(
    string ShellType,
    int? Cols = null,
    int? Rows = null,
    string? WorkingDirectory = null,
    TerminalTransportKind? Transport = null);

public sealed record CloseTerminalRequest(string? Reason);

public sealed record TerminalInputRequest(string Data);

public sealed record TerminalResizeRequest(int Cols, int Rows);

/// <summary>
/// Proves that a browser attachment heartbeat still belongs to the exact
/// gateway terminal incarnation that the browser originally attached to.
/// </summary>
public sealed record TerminalAttachmentRenewalRequest(ulong Generation)
{
    /// <summary>
    /// Opaque, server-issued fence for the persisted browser terminal handle.
    /// A successful ownership claim rotates this value so an older copied
    /// handle cannot renew the newly attached browser's lease.
    /// </summary>
    public string? AttachmentLeaseId { get; init; }

    /// <summary>Ephemeral ID generated by the browser runtime that sent this heartbeat.</summary>
    public string? BrowserAttachmentId { get; init; }

    /// <summary>
    /// True only for the first heartbeat from a newly loaded browser runtime.
    /// It permits an atomic hard-reload ownership handoff.
    /// </summary>
    public bool ClaimOwnership { get; init; }
}

public sealed record TerminalOpenResponse(string TrackingId, string SessionId, string Message);

public sealed record TerminalActionResponse(string TrackingId, string Message, string? SessionId = null, string? Code = null)
{
    /// <summary>
    /// The current opaque browser-attachment fence after a successful renewal.
    /// This is intentionally additive so existing action-response callers keep
    /// their original wire and constructor compatibility.
    /// </summary>
    public string? AttachmentLeaseId { get; init; }
}

/// <summary>
/// Browser-JavaScript callback result. A successful claim includes the current
/// lease fence so the same runtime can use it on subsequent heartbeats.
/// </summary>
public sealed record TerminalAttachmentHeartbeatResult(
    bool ShouldContinue,
    bool OwnershipConfirmed = false,
    string? AttachmentLeaseId = null);

public sealed record TerminalSessionDto(
    string SessionId,
    string ClientIdentityHex,
    string ShellType,
    string State,
    bool HasWebSocket,
    long CreatedUnix,
    long LastActivityUnix,
    string? CloseReason,
    string? Backend = null,
    int? Cols = null,
    int? Rows = null,
    IReadOnlyList<string>? Capabilities = null,
    TerminalTransportKind Transport = TerminalTransportKind.AkkaGateway,
    string? FailureCode = null)
{
    // Additive init property rather than a new positional constructor parameter:
    // this preserves already-built callers that invoke the original constructor.
    // Missing JSON remains null for older API responses and saved handles.
    public ulong? Generation { get; init; }

    /// <summary>
    /// Opaque browser attachment fence. It is stored with the non-secret V2
    /// handle and rotates when a newly loaded browser runtime claims ownership.
    /// </summary>
    public string? AttachmentLeaseId { get; init; }
}

public sealed record TerminalStreamMessage(
    string Kind,
    string? Data = null,
    string? Direction = null,
    ulong? Sequence = null,
    string? Reason = null,
    int? Cols = null,
    int? Rows = null,
    string? TimingId = null);

public sealed record TerminalDiagnosticsDto(
    string SessionId,
    TerminalTransportKind Transport,
    string State,
    long InputFrames,
    long OutputFrames,
    long InputBytes,
    long OutputBytes,
    double? ApiInputToDispatchP50Ms,
    double? ApiInputToDispatchP95Ms,
    double? AgentInputToPtyP50Ms,
    double? AgentInputToPtyP95Ms,
    double? AgentOutputToApiP50Ms,
    double? AgentOutputToApiP95Ms,
    double? ApiOutputToSseP50Ms,
    double? ApiOutputToSseP95Ms,
    string? LastStage = null,
    long? LastStageUnixMs = null);

public sealed record TerminalSelfTestRequest(
    string ShellType,
    TerminalTransportKind? Transport = TerminalTransportKind.ApiWebSocket,
    int? Cols = 120,
    int? Rows = 32,
    int? TimeoutMs = 8000);

public sealed record TerminalSelfTestResponse(
    string TrackingId,
    string SessionId,
    string ClientIdentityHex,
    string ShellType,
    TerminalTransportKind Transport,
    string Backend,
    bool Opened,
    bool FirstOutputReceived,
    long FirstOutputElapsedMs,
    string? OutputPreview,
    string? LastStage,
    bool CloseSucceeded,
    string? Error,
    IReadOnlyList<TerminalSelfTestStageDto>? Stages = null);

public sealed record TerminalSelfTestStageDto(
    string Stage,
    bool Succeeded,
    long ElapsedMs,
    string? Detail = null);
