// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NetRatel.Infrastructure.Persistence;

#nullable disable

namespace NetRatel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrchestratorDbContext))]
    [Migration("20260307175825_AddLegacyClientTaskIdToJobTaskActivity")]
    partial class AddLegacyClientTaskIdToJobTaskActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedScopesJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeviceInfoJson")
                        .HasColumnType("text");

                    b.Property<string>("DisabledReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("KeyAlgorithm")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ecdsa-p256");

                    b.Property<DateTimeOffset?>("KeyRegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastTokenIssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MtlsThumbprint")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CreatedAtUtc");

                    b.HasIndex("TenantId", "IsEnabled");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.AgentCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastUsedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.ToTable("AgentCredentials", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.AgentNonceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("AgentId", "Nonce")
                        .IsUnique();

                    b.ToTable("AgentNonceLogs", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.AgentRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastUsedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AgentId", "CreatedAtUtc");

                    b.ToTable("AgentRefreshTokens", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.AgentTokenEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AgentId", "CreatedAtUtc");

                    b.ToTable("AgentTokenEvents", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.EnrollmentCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedBy")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("Uses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "ValidToUtc");

                    b.ToTable("EnrollmentCodes", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientIdentity");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("TenantId");

                    b.HasIndex("FolderPath", "Name");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobParameterDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobParameters", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobRunRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStepOrdinal")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("InputsJson")
                        .HasColumnType("text");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StartedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientIdentity");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("JobId");

                    b.HasIndex("TenantId");

                    b.ToTable("JobRuns", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobStepDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Command")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("Runner")
                        .HasColumnType("text");

                    b.Property<long?>("ScriptId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("JobId", "Ordinal");

                    b.ToTable("JobSteps", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobStepRunRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<long>("JobRunId")
                        .HasColumnType("bigint");

                    b.Property<long>("JobStepId")
                        .HasColumnType("bigint");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TaskRequestId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId");

                    b.HasIndex("JobStepId");

                    b.HasIndex("JobRunId", "Ordinal");

                    b.ToTable("JobStepRuns", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobTaskActivityRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<long>("JobRunId")
                        .HasColumnType("bigint");

                    b.Property<long>("JobStepId")
                        .HasColumnType("bigint");

                    b.Property<int?>("LegacyClientTaskId")
                        .HasColumnType("integer");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("JobRunId");

                    b.HasIndex("JobStepId");

                    b.HasIndex("LegacyClientTaskId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("JobTaskActivities", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobTaskLogRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("JobTaskActivityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("Stream")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobTaskActivityId");

                    b.HasIndex("RequestId");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("RequestId", "Sequence", "Stream")
                        .IsUnique();

                    b.ToTable("JobTaskLogs", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.M2MConnectivitySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("RemoteAudience")
                        .HasColumnType("text");

                    b.Property<string>("RemoteBaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("RemoteSystemName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("M2MConnectivitySettings", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.OidcSigningKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrivateKeyPem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("KeyId")
                        .IsUnique();

                    b.ToTable("OidcSigningKeys", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("LockOwner")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NextAttemptUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EntityId");

                    b.HasIndex("OccurredUtc");

                    b.HasIndex("Type");

                    b.HasIndex("Status", "NextAttemptUtc", "LockedUntilUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.OutboxProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ProcessedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId", "ConsumerName");

                    b.HasIndex("ProcessedUtc");

                    b.ToTable("OutboxProcessedEvents", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.OutboxReadReceipt", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReadUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId", "ReadUtc");

                    b.ToTable("OutboxReadReceipts", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.RequestRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobInputs")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Logs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ResultData")
                        .HasColumnType("text");

                    b.Property<string>("ResultMessage")
                        .HasColumnType("text");

                    b.Property<string>("RundeckExecutionId")
                        .HasColumnType("text");

                    b.Property<string>("RundeckJobDefinitionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetClientIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("TargetClientIdentity");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("Requests", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.ScriptDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManifestJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScriptType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("FolderPath", "Name");

                    b.ToTable("Scripts", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.ScriptParameterDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Default")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<long>("ScriptId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScriptId");

                    b.ToTable("ScriptParameters", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.SecretRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientIdentity")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientIdentity");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("TenantId");

                    b.ToTable("Secrets", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Domains")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.AgentCredential", b =>
                {
                    b.HasOne("NetRatel.Infrastructure.Persistence.Agent", "Agent")
                        .WithMany("Credentials")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.AgentRefreshToken", b =>
                {
                    b.HasOne("NetRatel.Infrastructure.Persistence.Agent", "Agent")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobParameterDefinition", b =>
                {
                    b.HasOne("NetRatel.Infrastructure.Persistence.JobDefinition", "Job")
                        .WithMany("Parameters")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobRunRecord", b =>
                {
                    b.HasOne("NetRatel.Infrastructure.Persistence.JobDefinition", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobStepDefinition", b =>
                {
                    b.HasOne("NetRatel.Infrastructure.Persistence.JobDefinition", "Job")
                        .WithMany("Steps")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobStepRunRecord", b =>
                {
                    b.HasOne("NetRatel.Infrastructure.Persistence.JobRunRecord", "JobRun")
                        .WithMany("Steps")
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetRatel.Infrastructure.Persistence.JobStepDefinition", "JobStep")
                        .WithMany()
                        .HasForeignKey("JobStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobRun");

                    b.Navigation("JobStep");
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobTaskActivityRecord", b =>
                {
                    b.HasOne("NetRatel.Infrastructure.Persistence.JobRunRecord", "JobRun")
                        .WithMany("Activities")
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetRatel.Infrastructure.Persistence.JobStepDefinition", "JobStep")
                        .WithMany()
                        .HasForeignKey("JobStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobRun");

                    b.Navigation("JobStep");
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobTaskLogRecord", b =>
                {
                    b.HasOne("NetRatel.Infrastructure.Persistence.JobTaskActivityRecord", "Activity")
                        .WithMany("Logs")
                        .HasForeignKey("JobTaskActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.ScriptParameterDefinition", b =>
                {
                    b.HasOne("NetRatel.Infrastructure.Persistence.ScriptDefinition", "Script")
                        .WithMany("Parameters")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Script");
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.Agent", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobDefinition", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobRunRecord", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.JobTaskActivityRecord", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("NetRatel.Infrastructure.Persistence.ScriptDefinition", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
